<?

namespace rude\fb2;

require_once 'defines.php';

class chapter
{
	public $content = '';

	public function to_html()
	{
		$old = array(
			RUDE_FB2_REPLACE_IMG_OLD,
			RUDE_FB2_REPLACE_IMG_PROPERTY_SRC_OLD,
			RUDE_FB2_REPLACE_EMPTY_LINE_OLD,
			RUDE_FB2_REPLACE_CHAPTER_TITLE_OPEN_TAG_OLD,
			RUDE_FB2_REPLACE_CHAPTER_TITLE_CLOSE_TAG_OLD,
			RUDE_FB2_REPLACE_CHAPTER_SUBTITLE_OPEN_TAG_OLD,
			RUDE_FB2_REPLACE_CHAPTER_SUBTITLE_CLOSE_TAG_OLD,
			RUDE_FB2_REPLACE_CHAPTER_CONTAINER_OPEN_TAG_OLD,
			RUDE_FB2_REPLACE_CHAPTER_CONTAINER_CLOSE_TAG_OLD
		);

		$new = array(
			RUDE_FB2_REPLACE_IMG_NEW,
			RUDE_FB2_REPLACE_IMG_PROPERTY_SRC_NEW,
			RUDE_FB2_REPLACE_EMPTY_LINE_NEW,
			RUDE_FB2_REPLACE_CHAPTER_TITLE_OPEN_TAG_NEW,
			RUDE_FB2_REPLACE_CHAPTER_TITLE_CLOSE_TAG_NEW,
			RUDE_FB2_REPLACE_CHAPTER_SUBTITLE_OPEN_TAG_NEW,
			RUDE_FB2_REPLACE_CHAPTER_SUBTITLE_CLOSE_TAG_NEW,
			RUDE_FB2_REPLACE_CHAPTER_CONTAINER_OPEN_TAG_NEW,
			RUDE_FB2_REPLACE_CHAPTER_CONTAINER_CLOSE_TAG_NEW
		);


		$this->content = str_replace($old, $new, $this->content);
	}

	public function save($dir_path, $name, $extension = RUDE_FB2_TEXT_EXTENSION)
	{
		file_put_contents($dir_path . $name . '.' . $extension, $this->content);
	}
}